//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArabalar
    {
        public int id { get; set; }
        public string marka { get; set; }
        public string modelTarihi { get; set; }
        public string modeli { get; set; }
        public string yakit { get; set; }
        public string rengi { get; set; }
        public Nullable<bool> durumu { get; set; }
    }
}
